test:
  database: mini_reddit_test
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  database: mini_reddit_development
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  database: mini_reddit_production
  adapter: postgresql
  encoding: unicode
  pool: 5
